name: USeME
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - wandb==0.12.18
  - einops==0.4.1
  - seaborn==0.11.2
  - json5==0.9.5
  - pillow==9.1.0
  - numpy==1.22.3
  - scipy==1.8.0
  - pytorch-gpu=1.11
  - pytorch=1.11
  - pyjwt==2.3.0
  - tikzplotlib==0.10.1
  - matplotlib==3.5.1
  - torchmetrics==0.9.3
  - seaborn-base==0.11.2
  - hdf5==1.12.1
  - scikit-image==0.19.2
  - python==3.9.12
  - torchvision=0.12
  - pandas==1.4.2
  - h5py==3.6.0
  - pytorch-lightning==1.6.3
  - pywavelets==1.3.0
  - tqdm==4.64.0
  - cudatoolkit=11.2
  - jpeg
  - libpng
  - pip==22.0.4
  - pip:
    - resize-right==0.0.2

